version: "2.3"

services:

  ##
  # Debian Workspace
  ##
  gandamu:
    container_name: gandamu
    hostname: gandamu
    # build: .
    image: nobiki/gandamu:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      gandamu-net:
        ipv4_address: 172.10.0.100
    environment:
      - "TZ=Asia/Tokyo"
    command: /bootstrap.sh
    volumes:
      - ${PWD}/bootstrap.sh:/bootstrap.sh
      - ${PWD}:/home/vagrant/gandamu:ro
      - ${PWD}/gandamu/home/vagrant/.ssh/:/home/vagrant/.ssh/
      - ${PWD}/gandamu/var/workspace/:/var/workspace/
      - ${PWD}/gandamu/etc/supervisor/conf.d/:/etc/supervisor/conf.d/
      - ${PWD}/gandamu/etc/nginx/conf.d/:/etc/nginx/conf.d/
    tty: true

